### PR TITLE
Changing keys for min/max in Servo Calibration and updating some documentation

### PR DESCRIPTION
**Pull request by MZandtheRaspberryPi**
Hey Mike,

I'm still in awe of the awesome work you've done and software package you've put together. I'm going through step by step trying to get my spot working, and I am updating or adding to the documentation in your repo where I can. If its not useful or applicable, feel free to reject!

One small code change I made was moving the min/max move keys when configuring servo's for the first time. I accidentally hit "u" when trying to hit "y" to center my servo, and given body constraints drove the leg into another leg and did some damage to a servo. I figured moving the keys further away (I did z and x) could help. If you like they keys where they are, that's fine too though, I assume most folks will be better than me! I did update the documentation in the .md file as well as the screenshot of keyboard commands in the .md file.

I think i'm close to getting it walking, but I'm just debugging some poor calibration or something else going on. Thank you again for putting together this amazing software.

Best,
MZ

### CODE REVIEW

**Comment by mike4192** [comment]
Thanks for your contributions, I'll review it in the next few days. I'll need to deconflict the git modules file for some changes I've made.

Since you are at least one of the most active current users providing input, be aware I plan to start implementing significant changes in the next few weeks to better abide to ROS conventions so I can utilize more ROS packages for SLAM and motion planning. I'll try and keep things working for manual control as the repo is now.

BTW, one change I made recently is converting the ros_i2cpwmboard package to a submodule. Git doesn't elegantly handle when an existing directory is changed to a submodule. If you pull, I recommend deleting the ros_i2cpwmboard directory, after pulling, then restoring the missing directory, then running the git submodule init commands in the README.

**Comment by mike4192** [comment]
Looks good! I will squash and merge your pull request.

**Comment by MZandtheRaspberryPi** [comment]
Thanks for the heads up on the changes! It is much appreciated. I'm also
interested in SLAM and such--I have a small X4 Lidar from ydlidar that I
will look to integrate too, though I'm focused on getting the basics
working first. So, perhaps I can help with testing or changes or whatnot if
you want any help!

When you say, you recommend pulling, deleting the directory, restoring it,
then initializing once more, do you mean a git restore of that directory to
the prior commit before the merge?

**Comment by mike4192** [comment]
No, just manually deleting it.

So first pull the latest stuff, then delete the i2cpwmboard directory (`rm -rf ros-i2cpwmboard`), then re-create an empty directory (`mkdir ros-i2cpwmboard`) and then run the git submodule init commands.

**Comment by MZandtheRaspberryPi** [comment]
Got it, thank you!

**Pull request merged**
