### PR TITLE
Commands For Catkin and No Internet on Pi

### PR DESCRIPTION
**Pull request by MZandtheRaspberryPi**
Hi Mike,

I love all the work you've done and the documentation you've put together. I encountered some trouble when doing initial software setup on the pi and put some comments in in case other people encounter the same trouble. I was on a RPI4 and I didn't have internet on it as I'd already installed it into the robot and couldn't get access to the ethernet port. I also wasn't sure about killing the existing wifi config.

If this isn't applicable to others feel free to close or reject, and thanks again for putting together such a cool project and a guide!

Best,
MZ

### CODE REVIEW

**Comment by mike4192** [comment]
Thanks for contributing, this looks fine, I'll pull it in!

But I am curious why you aren't able to get internet on your RPi4? If it's connected to your local area network, which also has internet access, then the Pi should too.

**Comment by MZandtheRaspberryPi** [comment]
Hey Mike,

I didnt connect an ethernet cable to the pi and my home network because I
had already installed the pi in the robot and the pi's ethernet port was
difficult to get to with the long cable I had. Then, I didnt want to use
the Pi's wifi to connect to my home network as the ubiquity image was
already using the Pi's wifi to broadcast a network so that one could ssh
into the Pi. I didnt want to mess with that config, though perhaps that was
naive and inexperienced of me!

Did you connect your pi with an ethernet cable to your home network, so
that you were broadcasting a wifi network with the pi, and you were
connected to the internet through the ethernet cable and your home network?

**Comment by mike4192** [comment]
I see. In my setup, my raspberry pi is connected to my home network, as is my controlling computer. Messages are exchanged over the home network, and the raspberry pi has internet access. No ethernet cable involved. 

You can follow the instructions on this page to set up the pi with the ubiquiti image to connect to a different network, particularly the parts with the pifi commands:
https://learn.ubiquityrobotics.com/connect_network

**Comment by MZandtheRaspberryPi** [comment]
Ah, that's likely a better idea. Thanks for sharing the instructions on the
wifi setup. I think it will mostly be an indoor robot for me anyway so it
may be a good idea to have everything connected to a network with internet
as itll make troubleshooting easier too.

**Comment by mike4192** [comment]
Yes I highly recommend it. Additionally, I believe with this setup if one network is unavailable, such as the home network you configure, it will automatically revert to the other configuration, where you directly connect to the rpi.

**Comment by MZandtheRaspberryPi** [comment]
Wow that would be handy. Ok, thanks for sharing I'll definitely take a look!

**Comment by MZandtheRaspberryPi** [comment]
Fyi I did try the link you sent but my Pi4 couldnt found any wifi networks.
It does seem like a config issue, either something I did or something in
the image with Rpi 4. I'll take a look again later, but for will just host
the network from the Pi as that works by default for me.

Best,
MZ

**Comment by mike4192** [comment]
Hmm, that's unfortunate. Definitely could be something related to it being a rpi 4 instead of a 3.

My last suggestion is if your main PC has two network connections (like internet through ethernet, and raspberry pi to wifi), you could configure it to share internet to the pi through the wifi connection. I think it's a pretty easy setting to find in Ubuntus network settings gui.

**Pull request merged**
